### ISSUE TITLE
BulkimportDataSP.sql

### ISSUE THREAD

**Issue by adzzy** [rohitsies/GNAF-SSIS-Data-Loader#2]
Hi Just having a look at your data loader and cant see a script you talk about in the instructions BulkImportDataSP.sql

**Comment by rohitsies** [comment]
Thanks for highlighting. I have uploaded the file now... Below is the link:
https://github.com/rohitsies/GNAF-SSIS-Data-Loader/blob/master/BulkImportDataSP.sql
