### ISSUE TITLE
ssisconfig.dtsConfig

### ISSUE THREAD

**Issue by manu72** [rohitsies/GNAF-SSIS-Data-Loader#3]
Hi Rohit, 

I can't seem to find the ssisconfig.dtsConfig file in the zip download. I can see the details in the BulkLoadData.dtsx file but the configurations point to your F drive:

DTS:ConfigurationString="F:\Rohit\Work\GitProjects\Locations\SSISPackage\SSISImportData\SSISImportData\ssisconfig.dtsConfig

Am I missing something or is the file missing from the zip?

Thanks,
manu

**Comment by rohitsies** [comment]
Yes somehow it was missed while check in. Thanks for highlighting, I have uploaded that now:
https://github.com/rohitsies/GNAF-SSIS-Data-Loader/blob/master/GNAFSSIS/ssisconfig.dtsConfig
