### ISSUE TITLE
G-NAF\Extras folder is missing?

### ISSUE THREAD

**Issue by Mike-Honey** [rohitsies/GNAF-SSIS-Data-Loader#4]
Thanks for sharing this project - it looks interesting.

I cant find the G-NAF\Extras folder described in the readme.md, e.g. for:

G-NAF\Extras\GNAF_TableCreation_Scripts\create_tables_sqlserver.sql 

Can you add that please?

**Comment by rohitsies** [comment]
Hi Mike,

In Readme, First step mentions about downloading the zip file which contains the Extras folder.
Its around 1 GB of data and they keep on updating it so I didn't uploaded here in github although I provided the link for the same.
Go to below link
[https://data.gov.au/dataset/geocoded-national-address-file-g-naf](https://data.gov.au/dataset/geocoded-national-address-file-g-naf)
Under Data and Resources > May 2016 - PSMA Geocoded National Address ...> Explore > Go to resource.
This will download 1gb of data which contains the Extra folder which I mentioned.

Let me know if you need any more details.
